---
# Defines deployment design and assigns role to server groups

- hosts: ceph-clients # Gather facts for firewall
  sudo: yes

- hosts:
  - ceph-mon
  - ceph-osd
  - ceph-mds
  - ceph-rgw
  sudo: True
  roles:
  - ceph-common

- hosts: ceph-mon
  sudo: True
  roles:
  - ceph-mon

- hosts: ceph-osd
  sudo: True
  roles:
  - ceph-osd

- hosts: ceph-mds
  sudo: True
  roles:
  - ceph-mds

- hosts: ceph-rgw
  sudo: True
  roles:
  - ceph-radosgw
