---

- name: "update apt cache"
  action: apt update-cache=yes

- name: Restart Shorewall
  service: name=shorewall state=restarted

- name: Restart Shorewall6
  service: name=shorewall6 state=restarted

- name: "restart ceph"
  shell: service ceph restart ; service ceph-osd-all restart
  when: socket.rc == 0 and ansible_distribution == 'Ubuntu'

- name: "restart ceph"
  command: service ceph restart
  when: socket.rc == 0 and ansible_distribution == 'Debian' or ansible_os_family == 'RedHat'
