---
- name: Deploy Shorewall configuration.
  template: >
    src=shorewall/rules.j2
    dest=/etc/shorewall/rules.d/10_ceph
    mode=0644
    owner=root
    group=root
  notify: Restart Shorewall

- name: Deploy Shorewall6 configuration.
  template: >
    src=shorewall6/rules.j2
    dest=/etc/shorewall6/rules.d/10_ceph
    mode=0644
    owner=root
    group=root
  notify: Restart Shorewall6
