---
- name: Deploy Shorewall configuration.
  template: >
    src=shorewall/rules.j2
    dest=/etc/shorewall/rules.d/10_ceph
    mode=0644
    owner=root
    group=root
  notify: Restart Shorewall
  when: configure_firewall == True and not ipv6_only

- name: Deploy Shorewall6 configuration.
  template: >
    src=shorewall6/rules.j2
    dest=/etc/shorewall6/rules.d/10_ceph
    mode=0644
    owner=root
    group=root
  notify: Restart Shorewall6
  when: configure_firewall == True and 'ipv6' in hostvars[inventory_hostname]
